### ISSUE TITLE
缺少local_agent.yaml文件

### ISSUE THREAD

**Issue by Dhaizei** [THUDM/AgentBench#52]
warnings.warn(
Traceback (most recent call last):
  File "/root/anaconda3/envs/py38/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/py38/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/work/AgentBench/src/assigner.py", line 398, in <module>
    config_ = loader.load_from(args.config)
  File "/root/work/AgentBench/src/configs.py", line 51, in load_from
    raise e
  File "/root/work/AgentBench/src/configs.py", line 48, in load_from
    config = self.parse_imports(os.path.dirname(path), config)
  File "/root/work/AgentBench/src/configs.py", line 63, in parse_imports
    config = self.load_from(os.path.join(path, v))
  File "/root/work/AgentBench/src/configs.py", line 51, in load_from
    raise e
  File "/root/work/AgentBench/src/configs.py", line 48, in load_from
    config = self.parse_imports(os.path.dirname(path), config)
  File "/root/work/AgentBench/src/configs.py", line 77, in parse_imports
    raw_config[k] = self.parse_imports(path, v)
  File "/root/work/AgentBench/src/configs.py", line 77, in parse_imports
    raw_config[k] = self.parse_imports(path, v)
  File "/root/work/AgentBench/src/configs.py", line 72, in parse_imports
    config = self.load_from(os.path.join(path, vv))
  File "/root/work/AgentBench/src/configs.py", line 37, in load_from
    raise Exception("File not found: {}".format(path))
Exception: File not found: /root/work/AgentBench/configs/agents/local_agent.yaml

**Comment by zhc7** [comment]
Sorry, we've fixed that.
