### ISSUE TITLE
Could not use alfworld successfully

### ISSUE THREAD

**Issue by cyente** [THUDM/AgentBench#8]
根据 https://github.com/alfworld/alfworld 安装完成后，执行task依旧会有报错。

（这块的环境问题让人十分头疼，不知道是否有解决方案？）

```
Traceback (most recent call last):
  File "eval.py", line 99, in <module>
    main()
  File "eval.py", line 81, in main
    task = assignment.task.create()
  File "/mnt/workspace/xxx/pythonfile/download/AgentBench/create_assignment.py", line 43, in create
    return getattr(mod, self.module.split(".")[-1])(**self.parameters)
  File "/mnt/workspace/xxx/pythonfile/download/AgentBench/src/tasks/alfworld/task.py", line 28, in __init__
    mp.set_start_method('spawn')
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/context.py", line 243, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

**Comment by Longin-Yu** [comment]
Try our docker images? See https://github.com/THUDM/AgentBench/blob/main/docs/tutorial.md#step-2-prepare-docker-environment

**Comment by foamliu** [comment]
I removed all "multiprocessing" part then it worked.

**Comment by Longin-Yu** [comment]
If the issue still exists, please feel free to reopen this issue.
